export const items = [
  {
    id: 1,
    title: "McDonalds",
    description: "Big Mac Jumbo",
    image: "/mcd-img.png",
    status: "confirmed",
    orders: "400",
    amount: 9,
    placedOn: "6/3/22",
  },
  {
    id: 2,
    title: "Tesla",
    description: "Model X",
    image: "/tesla-img.png",
    status: "confirmed",
    orders: "5",
    amount: 3000,
    placedOn: "12/2/22",
  },
  {
    id: 3,
    title: "GM",
    description: "Alternator Car Parts",
    image: "/gm-img.png",
    status: "confirmed",
    orders: "32",
    amount: 49,
    placedOn: "19/4/23",
  },
  {
    id: 5,
    title: "Prime Theraputics",
    description: "Natural oil",
    image: "/prime-img.png",
    status: "confirmed",
    orders: "1,098",
    amount: 135,
    placedOn: "6/3/22",
  },
  {
    id: 6,
    title: "Match.com",
    description: "Renewal Subscription",
    image: "/match-img.png",
    status: "confirmed",
    orders: "4,298",
    amount: 48,
    placedOn: "12/2/22",
  },
  {
    id: 7,
    title: "Chevy",
    description: "FX234A",
    image: "/chevy-img.png",
    status: "confirmed",
    orders: "1,928",
    amount: 90,
    placedOn: "10/4/23",
  },
  {
    id: 8,
    title: "GM",
    description: "Car Parts AJZ89B",
    image: "/gm2-img.png",
    status: "confirmed",
    orders: "640",
    amount: 167,
    placedOn: "1/2/23",
  },
  {
    id: 9,
    title: "Piramal",
    description: "Medical Equipment",
    image: "/prime-img.png",
    status: "delivered",
    orders: "18",
    amount: 105,
    placedOn: "4/5/23",
  },
  {
    id: 10,
    title: "Matchelin",
    description: "Car parts",
    image: "/match-img.png",
    status: "delivered",
    orders: "498",
    amount: 48,
    placedOn: "1/2/22",
  },
  {
    id: 11,
    title: "Chevery",
    description: "CAH0113",
    image: "/chevy-img.png",
    status: "refunded",
    orders: "18",
    amount: 190,
    placedOn: "4/9/22",
  },
  {
    id: 12,
    title: "GM",
    description: "Machinery AJZ89B",
    image: "/gm2-img.png",
    status: "refunded",
    orders: "60",
    amount: 17,
    placedOn: "16/3/22",
  },
  {
    id: 13,
    title: "GM Dev",
    description: "Medical equipments",
    image: "/tesla-img.png",
    status: "pending",
    orders: "52",
    amount: 225,
    placedOn: "4/9/22",
  },
  {
    id: 14,
    title: "AARP",
    description: "Machinery",
    image: "/prime-img.png",
    status: "pending",
    orders: "64",
    amount: 640,
    placedOn: "1/7/22",
  },
];
